name: Version Bump and Tag

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  version_bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Determine Version Bump Type
        id: bump_type
        run: |
          if [[ "${GITHUB_REF##*/}" == feat:* ]]; then
            echo "BUMP_TYPE=minor" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == fix:* ]]; then
            echo "BUMP_TYPE=patch" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == major:* ]]; then
            echo "BUMP_TYPE=major" >> $GITHUB_ENV
          else
            echo "BUMP_TYPE=patch" >> $GITHUB_ENV # default to patch if no prefix

      - name: Bump Version in package.json
        run: |
          npm version ${{ env.BUMP_TYPE }} --no-git-tag-version
          VERSION=$(jq -r '.version' package.json)
          git add package.json package-lock.json
          git commit -m "Bump version to $VERSION"
          git tag "v$VERSION"
          git push origin HEAD --tags

