name: Version Bump and Tag

on:
  pull_request:
    branches:
      - 'develop'  # Target branch for PRs (typically the main development branch)

jobs:
  version_bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Check for Version Bump Label
        id: check_label
        run: |
          # Check if the PR has a 'version-bumped' label
          LABELS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels | jq -r '.[].name')

          if echo "$LABELS" | grep -q "version-bumped"; then
            echo "SKIP_BUMP=true" >> $GITHUB_ENV
          else
            echo "SKIP_BUMP=false" >> $GITHUB_ENV
          fi

      - name: Determine Version Bump Type
        if: env.SKIP_BUMP == 'false'
        id: bump_type
        run: |
          if [[ "${{ github.head_ref }}" == feat:* ]]; then
            echo "BUMP_TYPE=minor" >> $GITHUB_ENV
          elif [[ "${{ github.head_ref }}" == fix:* ]]; then
            echo "BUMP_TYPE=patch" >> $GITHUB_ENV
          elif [[ "${{ github.head_ref }}" == major:* ]]; then
            echo "BUMP_TYPE=major" >> $GITHUB_ENV
          else
            echo "BUMP_TYPE=patch" >> $GITHUB_ENV # default to patch if no prefix
          fi

      - name: Configure Git User
        if: env.SKIP_BUMP == 'false'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Bump Version in package.json
        if: env.SKIP_BUMP == 'false'
        run: |
          # Bump the version in package.json based on the bump type
          npm version ${{ env.BUMP_TYPE }} --no-git-tag-version
          VERSION=$(jq -r '.version' package.json)
          
          # Commit the version bump changes
          git add package.json package-lock.json
          git commit -m "chore: bump version to $VERSION"
          
          # Pull any remote changes on the PR branch to prevent conflicts
          git pull origin "${{ github.head_ref }}" --rebase
          
          # Push the updated version back to the PR branch
          git push origin "HEAD:${{ github.head_ref }}"

      - name: Add Version Bumped Label
        if: env.SKIP_BUMP == 'false'
        run: |
          # Add the 'version-bumped' label to the PR to prevent repeat bumps
          curl -s -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
            -d '{"labels":["version-bumped"]}'
