name: Version Bump

on:
  pull_request:
    branches:
      - develop  # Change this if you want it on a different branch

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Bump minor version
        run: |
          node -e "let pkg = require('./package.json'); pkg.version = pkg.version.replace(/(\d+)\.(\d+)\.(\d+)/, (_, major, minor, patch) => \`\${major}.\${+minor + 1}.0\`); require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
          
      - name: Commit version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: bump minor version"

      - name: Push changes
        run: git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
