name: Version Bump

on:
  pull_request:
    branches:
      - 'develop'  # Target branch for PRs (typically the main development branch)

jobs:
  version_bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Check for Version Bump Label
        id: check_label
        run: |
          LABELS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels | jq -r '.[].name')

          if echo "$LABELS" | grep -q "version-bumped"; then
            echo "SKIP_BUMP=true" >> $GITHUB_ENV
          else
            echo "SKIP_BUMP=false" >> $GITHUB_ENV
          fi

      - name: Determine Version Bump Type
        if: env.SKIP_BUMP == 'false'
        id: bump_type
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ "$BRANCH_NAME" == feat/* ]]; then
            echo "BUMP_TYPE=minor" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == fix/* ]]; then
            echo "BUMP_TYPE=patch" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == major/* ]]; then
            echo "BUMP_TYPE=major" >> $GITHUB_ENV
          else
            echo "BUMP_TYPE=patch" >> $GITHUB_ENV
          fi

      - name: Configure Git User
        if: env.SKIP_BUMP == 'false'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Bump Version in package.json
        if: env.SKIP_BUMP == 'false'
        run: |
          npm version ${{ env.BUMP_TYPE }} --no-git-tag-version
          VERSION=$(jq -r '.version' package.json)
          git add package.json package-lock.json
          git commit -m "chore: bump version to $VERSION"
          git pull origin "${{ github.head_ref }}" --rebase
          git push origin "HEAD:${{ github.head_ref }}"

      - name: Add Version Bumped Label
        if: env.SKIP_BUMP == 'false'
        run: |
          curl -s -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
            -d '{"labels":["version-bumped"]}'
