name: Version Check

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  check-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history for accurate diff detection

      - name: Check for package.json and package-lock.json changes
        run: |
          BASE_BRANCH=$(echo "${{ github.base_ref }}")
          PACKAGE_CHANGED=$(git diff --name-only origin/$BASE_BRANCH HEAD | grep -q "package.json" && echo "true" || echo "false")
          LOCK_CHANGED=$(git diff --name-only origin/$BASE_BRANCH HEAD | grep -q "package-lock.json" && echo "true" || echo "false")

          if [ "$PACKAGE_CHANGED" = "true" ] && [ "$LOCK_CHANGED" = "false" ]; then
            echo "Error: package-lock.json must be updated whenever package.json is modified." && exit 1
          elif [ "$PACKAGE_CHANGED" = "false" ] && [ "$LOCK_CHANGED" = "true" ]; then
            echo "Error: package.json should also be updated if package-lock.json changes." && exit 1
          else
            echo "Check passed: package.json and package-lock.json are in sync."
          fi
